#!/usr/bin/env python

import json
import os
import subprocess
import sys
import debugpy

def log(line: str):
    print(line, flush=True)

def load_environment_file(file: str) -> bool:
    if not os.path.exists(file):
        log(f"Unable to load env from file {file}, file does not exist.")
        return False
    log(f"Loading environment variables from file '{file}'")
    try:
        with open(file, 'r') as fh:
            variables = json.load(fh)
            for key, value in variables.items():
                if isinstance(value, bool):
                    value = str(value).lower()
                if key not in os.environ:
                    os.environ[key] = str(value)
    except json.JSONDecodeError:
        log(f"Error decoding JSON from {file}")
    except Exception as err:
        log(f"An error occurred while loading config variables: {err}")
    return True


load_environment_file(os.path.join("config", "environment_variables.json"))
load_environment_file(os.path.join("config", "environment_variables-template.json"))

log("Running 'manage.py makemigrations'")
os.system("python manage.py makemigrations")
log("Running 'manage.py migrate'")
os.system("python manage.py migrate")
log("Running 'manage.py createsuperuser'")
os.system("python manage.py createsuperuser --noinput")
initial_dev_user = os.environ.get('DEV_VOTER_INITIAL_USER', "Samuel Adams samuel@adams.com ale")
log(f"Running 'manage.py create_dev_user {initial_dev_user}'")
os.system("python manage.py create_dev_user " + initial_dev_user)

# Start debugpy listener
try:
    log("Starting debugpy on 0.0.0.0:5678")
    debugpy.listen(("0.0.0.0", 5678))

    log("Debugger is ready and waiting for VS Code or PyCharm to attach...")
except Exception as e:
    log(f"Error starting debugpy: {e}")

if os.environ.get('DEV_SERVER_TYPE', 'runserver') == 'runsslserver':
    new_args = ['python', 'manage.py',
                os.environ.get('DEV_SERVER_TYPE', 'runserver'),
                f"{os.environ.get('DEV_SERVER_DOMAIN', 'localhost')}:{os.environ.get('DEV_SERVER_PORT', '8000')}",
                '--certificate', os.environ.get('DEV_SERVER_SSL_CERT', 'cert/wevotedeveloper.com.crt'),
                '--key', os.environ.get('DEV_SERVER_SSL_KEY', 'cert/wevotedeveloper.com_key.txt')]
else:
    new_args = sys.argv[1:]
log(f"Running app startup command: {' '.join(new_args)}")
sys.exit(subprocess.call(new_args))
