# Generated by Django 5.2.16 on 2026-09-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0019_alter_batchprocess_kind_of_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrowactionballotitem',
            name='referendum_con',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='batchrowactionballotitem',
            name='referendum_pro',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='batchrowactionmeasure',
            name='referendum_con',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='batchrowactionmeasure',
            name='referendum_pro',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
