FROM public.ecr.aws/docker/library/python:3.12-slim-bookworm

# install required software
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && apt install -y \
    libcairo2 postgresql-client libmagic1

# install python dependencies
COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt --no-cache-dir && \
    pip install debugpy

# copy entrypoint script
COPY docker/dev/entrypoint /usr/local/bin/docker-entrypoint

# setup user and create required directories
RUN useradd wevote && mkdir -p /var/log/wevote /wevote && chown wevote:wevote /var/log/wevote /wevote

# define docker runtime
WORKDIR /wevote/code
USER wevote
EXPOSE 8000
EXPOSE 9000
EXPOSE 5678
EXPOSE 5432

ENTRYPOINT ["docker-entrypoint"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

