FROM python:3.9-slim-buster

RUN apt update && \
	apt install -y g++ gcc \
		libpq-dev zlib1g-dev \
		libffi-dev libjpeg-dev \
		libmagic-dev

COPY requirements.txt .

RUN python -m pip install -r requirements.txt --no-cache-dir

EXPOSE 8000
WORKDIR /wevote
ENTRYPOINT /wevote/docker/entrypoint_api_server.sh


