FROM python:3.9-alpine

RUN apk add g++ gcc
RUN apk add musl-dev postgresql-dev zlib-dev libffi-dev jpeg-dev
RUN apk add postgresql-libs libmagic

COPY requirements.txt .

RUN python -m pip install -r requirements.txt --no-cache-dir

EXPOSE 8000
WORKDIR /wevote
ENTRYPOINT /wevote/docker/entrypoint_api_server.sh


