FROM public.ecr.aws/docker/library/python:3.12-slim-bookworm

# install required software
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    && curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/postgresql-archive-keyring.gpg] http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && apt-get update && apt-get install -y \
    libcairo2 postgresql-client-16 libmagic1 \
    && rm -rf /var/lib/apt/lists/*

# install python dependencies
COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt --no-cache-dir

# install New Relic Python agent for application performance monitoring
#RUN pip install newrelic

# install OpenTelemetry instrumentation for Python and Django
RUN pip install opentelemetry-distro opentelemetry-instrumentation-django opentelemetry-exporter-otlp
RUN opentelemetry-bootstrap -a install

# copy entrypoint script
COPY docker/prod/entrypoint /usr/local/bin/docker-entrypoint

# COPY database migration script
COPY docker/prod/run-db-migration /usr/local/bin/run-db-migration

# setup user and create required directories
RUN useradd wevote && mkdir -p /var/log/wevote /wevote && chown wevote:wevote /var/log/wevote /wevote

# copy all repo files to container
COPY . /wevote/code

# change ownership of migrations directories
RUN for d in `find /wevote/code -name migrations -type d`; do \
    chown wevote:wevote $d; \
done

# define docker runtime
WORKDIR /wevote/code
USER wevote
EXPOSE 8000

ENV RUNNING_IN_DOCKER=True

ENTRYPOINT ["docker-entrypoint"]
CMD ["opentelemetry-instrument", "gunicorn", "--workers", "2", "--threads", "4", "--worker-class", "gthread", "--timeout", "1800", "--bind", "0.0.0.0:8000", "config.wsgi"]
#CMD ["newrelic-admin", "run-program", "gunicorn", "--workers", "2", "--threads", "4", "--worker-class", "gthread", "--timeout", "1800", "--bind", "0.0.0.0:8000", "config.wsgi"]

