# Generated by Django 5.0.13 on 2026-05-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql=f"""
                CREATE TABLE IF NOT EXISTS wevote_server_cache (
                    cache_key varchar(255) PRIMARY KEY,
                    value text NOT NULL,
                    expires timestamp with time zone NOT NULL
                );

                CREATE INDEX IF NOT EXISTS idx_wevote_server_cache_expires
                ON wevote_server_cache(expires);
            """,

            reverse_sql=f"""
                DROP TABLE IF EXISTS wevote_server_cache;
            """
        ),
    ]