# Generated by Django 5.0.13 on 2026-08-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0047_politiciansupporter_added_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='politician_email_subscription_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
