# Generated by Django 5.2.16 on 2026-09-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0005_contestmeasuresarepossibleduplicates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestmeasure',
            name='referendum_con',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contestmeasure',
            name='referendum_pro',
            field=models.TextField(blank=True, default=''),
        ),
    ]
