# Generated by Django 5.2.16 on 2026-09-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0006_contestmeasure_referendum_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestmeasure',
            name='referendum_con',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contestmeasure',
            name='referendum_pro',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
