# Generated by Django 5.2.16 on 2026-09-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0008_ballotitem_election_state_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotitem',
            name='referendum_con',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='ballotitem',
            name='referendum_pro',
            field=models.TextField(blank=True, default=None),
        ),
    ]
