# Generated by Django 5.2.16 on 2026-09-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0009_ballotitem_referendum_con_ballotitem_referendum_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotitem',
            name='referendum_con',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ballotitem',
            name='referendum_pro',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
